sl1:
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Sumxex"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "MC2"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge Jump Equal Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge PL Equal Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge Kink Equal Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge Finance Equal Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge Smooth Equal Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge JSU Equal Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge Jump Sparse Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge PL Sparse Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge Kink Sparse Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge Finance Sparse Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge Smooth Sparse Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Ridge JSU Sparse Weights"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Genz Oscillatory 1"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Genz Oscillatory 2"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Genz Oscillatory 3"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Genz Corner-Peak 1"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Genz Corner-Peak 2"
	python examples/budgeted_comparison/experiment.py -d 1 --outdir SL/d1/ --parallel 10 -p "Genz Corner-Peak 3"
