[project]
name = "mlqmcpy"
version = "0.0.1"
description = "Multilevel quasi-Monte Carlo in Python."
dependencies = [
    # "boost-histogram>=1.5.1",
    "numpy>=2.2.2",
    "qmcpy>=2.0.0.1c4",
    "prettytable>=3.5.0",
    "fastgps>=1.0.0.1b8",
    "torch>=2.6.0",
]
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "isort>=6.0.0",
    "ruff>=0.9.6",
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
    "jupyterlab>=4.4.2",
    "matplotlib>=3.10.1",
    "pyslope>=1.2.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mlqmcpy"]

[tool.black]
line-length = 88
target-version = ["py313"]

[tool.ruff]
line-length = 88

[tool.isort]
profile = "black"